
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-report:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: java-assignment
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: temurin
          cache: maven

      - name: Run Maven tests
        run: mvn -B clean verify

      - name: Prepare jacoco coverage
        uses: cicirello/jacoco-badge-generator@v2
        id: coverage
        with:
          jacoco-csv-file: java-assignment/target/site/jacoco/jacoco.csv

      - name: Log coverage
        run: |
         echo "Coverage: ${{ steps.coverage.outputs.coverage }}%"
