name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Run Maven tests with JaCoCo
        run: mvn -B clean verify jacoco:report jacoco:check \
          -Djacoco.check.skip=false \
          -Djacoco.check.rules= \
          -Djacoco.dataFile=target/jacoco.exec
        working-directory: ./java-assignment

